### ISSUE TITLE
CCAI/RIN on Solana -> WWT  on ETH

### ISSUE THREAD

**Issue by m4t123** [solana-labs/oyster#231]
Hey again ! Thanks for helping out so fast in the afternoon, but now i got another problem while bridging token from solana -> eth.

So, normal user flow and i clicked approve on solana and it never went further or asked for the ethereum transaction.
https://solscan.io/tx/2Y4hCuBEynfFCB7rWEuegYiraggkiiCtoPtsP4zB7AUkkgyj9CRgNGWwYLHHZTxUm68duoBCMZuJzqqghWschvMY

I also checked other transactions and it seems only my tokens get "lost". 
Since i never had these issues before, do i use an old deprecated bridge or something? I do not understand why it never happend in a few months, but now twice in a few hours. Is there maybe a rate limit issue with the rpc or anything?

Thanks for your help!

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: 1https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 21676d1518182b59f579c8e7893d3fa15dc5c4e6a47c6cc83e9f42dd774b3cf9

Signed VAA bytes to submit to the contract:

> 0x01000000010d001febb4c6ae87c85b680ca0f4930233322901bb064d0945398d8664670a3284111b6b219e0a32fcd3896e7fef4b094cc66134764fe994d885fc7c39580dec9d7f0001dca1b48bb27fa759fc4cca71b0fdb205678fd6439c7e3aa395a03bfabd4cb58b1efe73e94dd93980ccb94ded6188e48617d7f4197f5af2bb91450a64a613e9800002cd01c3476e78278ab4b75f3940800083aa30b03e75443d54cbf4d16ce678c5ca3c44773fd62e1aef6aeceab3b8fa1999245f907c3bed4f679f29e0d306624cdb0005e39e33edd74becf7951fc7b12279f4d90d204fd9429764f22653c0b3013683542b768cad723e257c70add517a4d9071a4ba370a1a1b80badddb545c1d12cc18c010685001aaef635c19d2fc9eda173be1f6d283c50bf234f13da45d5dd55a6d75cec0b418ecd45633e94df9730de55fcc62801f335e74565330ce2651694a19e7c290007aab35f5bff3cb4b6269ff8bfade34f64307793a08e2a0278eee3a7acd35be17c19cd98c357d9085d9bde48a6f6b50241e666ee413667b0767697c2238e134c5c00098f584d047aed0f6d9935edd704c3293e69e57f5e5da370d5e67202a9ec87bf887bd5b0d08bae1da257a688a7389be2c8a173e0a32776c5ea25021339cd304546010a83fc1b0ad9c95b36113faab75b4765b691eb135e72e27e3c1db67d21507ad91f2890596c6e87c991d2d55561f902d9d41b2b86ac51753dd41260d47172e845ca000bf5d4bb93ad463602f427b7ec78affd35e69138c496dfc8121a7696f8eae84f841cf0a666ba38b4ec659f8db2023aa87d01f9531501877109c655aed69b178455000d24cb9d97052a416e556e4da1b9b6b55952520a9b22e385e6f135c00228b7063b38c091c495192824186ebeab79d649c11b3fb29db2e9b5a604141d9e2bee326f0010dbfc34fccef351b120b69a12f7fe6f81e66b8947117f0831eb0aef0419b3d95824ba633fe5583db8accf8a69d210cf5e617b74dfa357de1d345055e6e71cb8a10011725250876904c1d8add4760d99db331d65ff94c7fdb97f5827b334f3a67e63944ec0bed1eae0577719bcbd429ee9bd8651670733df0bcfcebd6b9dcbb2c470ad0012d37c39a9f88e147cb4e569a469fbfc176e79f054e9992971509dda28b022ef245b9068088a354ef770106f19e7b182952a5ccdb9c9900d4602dad3f780e36ed401612ed1b81000003a40010249c36d3d422f0d4485c42e252d9128e1f7a5cf57b896e8a77de479e45be64404000000000000000000000000e7207afc5cd57625b88e2ddbc4fe9de794a76b0f01c261d86cf5cf877128ba1f5652e5f3dda599270c1556a15bc0a9aacf8063e563090000000000000000000000000000000000000000000000000000001e449a9400

---

> Since i never had these issues before, do i use an old deprecated bridge or something? I do not understand why it never happend in a few months, but now twice in a few hours. Is there maybe a rate limit issue with the rpc or anything?

I seems to be related to the high load on the mainnet RPC endpoints right now due to the influx of new Solana users for the past couple days, so a small % of transactions get stuck in a state the UI can't automatically recover from.

**Comment by leoluk** [comment]
Unfortunately not, it's a manual process. Wormhole v2 will have an automated way to complete interrupted transfers
