### ISSUE TITLE
Wormhole Transfer Lost-WRENBTC

### ISSUE THREAD

**Issue by tosunra** [solana-labs/oyster#258]
Hello , i transfer wrenbtc from Solana to Eth( wormhole) , i refresh the page, and the wrenbtc was sent, but i can not get them in my eth wallet. It just show In Process, how can i do now? Please help.

https://explorer.solana.com/tx/L67137mcs84KefCyH9WRauCG88VwH9fKFHWJrQ4WnQF2gKeDhx7ZYTR4R1cWjmX4nRF9i8cYSv94mNGqaHuZBEj

**Comment by pseudoanonymous-eth** [comment]
The issue is you need to call "Submit VAA" from your ETH address with the proper byte code
this acct @hx8888979 wrote a script to generate that byte code based on your solana TX. try it https://www.interstellar.tk/
I was able to use it no problem, so am sharing it to others with this issue
they put the option to tip fyi, if it all works well for you

**Comment by tosunra** [comment]
Thank you very much. It help.
