### ISSUE TITLE
Tokens appeared as something else at the end of the wormhole, and stuck on the way back

### ISSUE THREAD

**Issue by andydhancock** [solana-labs/oyster#290]
I sent my SRM thru the wormhole from ETH to SOL (I realise later I could have used sollet)
They didn't appear as SRM though but some other token.
TX: 5rq4HNp3Qin7tGox3GUicERpi4b8CXnWvCPpyHcZoG1W7Z98pTyib2Gkohy87pUPpj5TVu2RqG3xycahyxyYhN5v
So I tried sending back, but cancelled the metamask window as the wallet had changed.
So now it's stuck. I realise I can use interstellar.tk to get it back, but it means paying lots of gas to get them where I don't want them to be.
TX: Psc6GDpEjW6Juf35VGKNLCgqeV8kp1iCauimGBWbzgWyaFdRAyjsb835z3SM6ZAJJaYKCmEbtbZcgqhe6PYvRz3

**Comment by leoluk** [comment]
> They didn't appear as SRM though but some other token.

You got wSRM which are recognized by Saber, for example.

There is no way to cancel a Wormhole transfer other than completing it (it wouldn't be safe to do so, since the originating chain has no way of knowing whether the VAA was completed or not).

You need to complete the transfer by using https://www.interstellar.tk or following these instructions:

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): a446a5044e04dc82dd7ab94c063cd95f19f533fac104eaacb26a737f326d1e17

Signed VAA bytes to submit to the contract:

> 0x01000000010d00451c475f479c6953b9e289bf059f8afe2b97c7ee9c1ced83f5aded106d7a660c1e92025dab405101166c1571da20342ee3acb8a89338066a7ede57142ee99ed40101bc6d68fe17729613e0f1049c3c22e8840d67a8cc0b3ffe0563aaf3de8ab7ea6f7da02a136800bacfcf87440e786fa294b0497d379b1dd1b269ec51a26092eac80003aec0f35142d64d086293dc5a2a35dab82df4edcd61d347de2e0840e183639231537e1a46e2d282a5b978911ee260465e38449a9dce969d35970cdd630b644bb60004a3e0be7d9f8864ba55df24d25816c21bba767ae7146ff39def30165b6b57f45e34fa0f56a9f7aa620ffd41d213f7041cf9c9c4b518e4b958cab57becd4cdb28800052bc8256a8e48ec6614ee37279f18f2ef2c868cd22593db7bc5d602a4ffd74a68482327367b260f4b2df81fe8d78f1995bbef10f44864fb1189bb08b230d23f89010799b9ad60328b06787e9c5bd5ac8653b418d16ad5997f327d395104ba7a4010387a1b3440367fdcd991284e4ffd38f4c70ad6d3ec486154bc8ac51f63e616d1b100088f60a98d7c49fe58872a31bd372a33d61ecef9e85c53ad948bb88c6bcee6e4a259cc197523e61b1b5ca976182e5522dae33168655ba020f0c5ebcca0f6394f5001094ba6c4fdff82dd034c6c08ac81e1a597eb7c7fc3249daa8fba4af40c804a0d0f1b0333c5f95e56cf4ba2673bd533fa2557c2cfa42ee145e56091e1c529810c2a000aabc5f3c995602ef34a76760a3219715fde9b39f7cc427f68c2e78b2126cae1ea22e006b2dd1fcfb4dc3482b0980f75fab8a020ecc9292e344dfc0372290c0edc010b99433bfc9c4ae0acd87a57e21494abe6e56d2bf080a8195c8125a5a4a93d0cab271ad8e9401b1cf8fd6fd4d94fd248b986ea5f7a82ea0dc6ac0bd53f1aca8910000d57f8db8b661569ff2c9a0d292e4ad544e94c8d61369032940b622796416427260e8473b3a7cd4006fbf59bdbf08ecc873042cbd1f14e96fbd05d428919ef513f00111294b4d0f7e71923003059fce0dbc2928d02917c2b1a0e0087a08ba3bea90304760c83ba28f9bc7cdee13b51a3767501cb14e0e83e2b348cd8921017e9d1f6380112a923d160aceb68962c4c2150b96386bf67d727074403b8415c6609a9054f7f1c1b531bde5ece0a0e41fb8d7caea304014639422a677f1471a57ba2e4f9293c5b006139e08010000137dd0102fba48e4f7a44a676915d23bba3211b858c8b69c5a54d64e831e464d0635d0f740000000000000000000000009575e331988058247f27ffcd1b9620f10df028a802000000000000000000000000476c5e26a75bd202a9683ffd34359c0cc15be0ff060000000000000000000000000000000000000000000000000000000010ed822e
