### ISSUE TITLE
The recovery procedure doesn't go as expected

### ISSUE THREAD

**Issue by changtimwu** [solana-labs/oyster#457]
I tried to transfer 0.1 SOL to ethereum and it failed due to insufficient fee in my eth wallet.  The fund seem stuck in your so called "bridge".   Now I'd like to abort the transfer and just take my SOL back.   

I followed the recovery procedure and entered the txid in "Redeem" tab.  It brough me to the "Tokens" tab.  However,  the "target" field still shows "to 0x2f...c3d6on Ethereum".    This confuses me.   Isn't the recovery should be just between my solana wallet and your bridge?

**Comment by leoluk** [comment]
This repo is for Wormhole v1 only: please reach out to the Wormhole Network Discord instead: https://wormholenetwork.com

(the redeem tab completes the transfer - there's no way to abort a transaction due to the cross-chain nature of the transfer, the sending blockchain has no way of knowing whether or not the transfer was redeemed)
